### ISSUE TITLE
lab 1

### ISSUE THREAD

**Issue by MansMeg** [STIMALiU/IntroStatsForCSCourse#11]
Plotta både simulerade data och pdf:en i samma graf (där det går).

**Comment by mattiasvillani** [comment]
Uppgift 6 heter Markovmetoder. Menade du Monte Carlo-metoder? Varför Markov?

**Comment by mattiasvillani** [comment]
Förslag: minska ner på antalet uppgifter och lägg till en mer komplex situation som löses med simulering. Kanske ett beslutsproblem med lagerhållning där ett företags efterfrågan följer en viss fördelning. Maximera förväntad vinst.

**Comment by mattiasvillani** [comment]
Kanske andelen  defekta varor (p) ökar när man producerar mer (stress i fabriken ...). Antalet defekta är Poisson med n*p, där är produktionsvolymen. Endast de icke-defekta kan säljas. Efterfrågan är slumpmässig. Förväntad vinst. Du fattar.

**Comment by mattiasvillani** [comment]
Uppgift 3. Du skriver att de tre variablerna konvergerar mot en annan sannolikhetsfördelning. Lite otydligt eftersom x2 följer en exakt fördelning (dvs man behöver inte tala om konvergens för denna slumpvariabel. Vi vet exakt vilket fördelningen den har).

**Comment by MansMeg** [comment]
Markov är fel. Ska självklart vara MC.

**Comment by MansMeg** [comment]
Hej!

Japp. Exp(1) + Exp(1) konvergerar inte. Fel där, sorry igen. Kanske byta ut mot:
If X_i ~ U(0, 1)
min(X_1,...,X_n) as n-> infty
?

Då visar vi på lite "konstigare" funktioner som också kan konvergera i fördelning.

**Comment by mattiasvillani** [comment]
Uppgift 9 är lite otydlig. Under a) 'Skriv en loop/funktion i R som drar 10 värden från X och Y ...'. Ska man dra nya slumpvariabler hela tiden, eller dra med återläggning från de 1000 som genererades i början av uppgiften?

**Comment by mattiasvillani** [comment]
Uppgift 3. Ditt förslag med min(X_1,...,X_n) as n-> infty konvergerar mot en punktmassa i nollan?

**Comment by MansMeg** [comment]
Mycket småfel nu. Missade n .

> n min(X_1,...,X_n) as n-> infty menar jag.

**Comment by MansMeg** [comment]
Jag tror jag nu löst detta. Finns en mer komplex uppgift (dock ej lagerhållning utan val av system), tagit bort gamma och bytt till MC isf Markov. Samt lagt till att visualiser pmf/pdf i vissa fall. Se ff700fe .
