### ISSUE TITLE
Erfarenheter från Labb 2

### ISSUE THREAD

**Issue by Taloie** [STIMALiU/IntroStatsForCSCourse#27]
På Uppgift 4, i pseudo koden så står det att man ska ge "norm_sigma2_mle" parametrarna x = y1 och mu = 10, men enligt websidan som vi länkades till https://en.wikipedia.org/wiki/Normal_distribution#Estimation_of_parameters så tolkar vi det som att funktionen inte tar mu som indata. Detta speciellt då den inte gör det i exemplen på uppgift 3. Vad är det som gäller, och vilken funktion borde "norm_sigma2_mle" egentligen vara då? 

edit:
Vi är även lite förvirrade då det vi i pseudokoden ser ut att göra 10 och 100 dragningar (n = 10 och n = 100) men i fråga a) så står det att man ska visualisera för n = 10 och n = 10 000. Är något av talen fel eller ska man utöver för 10 och 100 simulera en separat för 10 000?

**Comment by MansMeg** [comment]
Jag ska försöka titta på detta imorgon! Tack!

**Comment by Taloie** [comment]
Utöver detta så skulle ett förtydligande av vad som ska göras på uppgift 1e) uppskattas. Det som förvirrar oss är hur och vad vi ska visualisera i histogram.

**Comment by MansMeg** [comment]
Nu ska detta vara fixat. Tack!
