### ISSUE TITLE
Generellt för laborationerna

### ISSUE THREAD

**Issue by MansMeg** [STIMALiU/IntroStatsForCSCourse#7]
Hänvisa till avsnitt i kursboken för olika uppgifter. Bygg mer på att de måste läsa i boken eller i slidsen för att klara uppgiften.
Kräv att de upprepar frågorna i laborationsrapporten, kanske fixa en mall?
Använd LISAM så det går att kommentera i dokumenten som sedan skickas tillbaka. 
Vissa funktioner kan vi använda MMA för. 

Se till att uppgiftsnumret finns med i labben (ex. 1e) o.s.v

**Comment by mattiasvillani** [comment]
LISAM fixat nu.

**Comment by MansMeg** [comment]
Fixat med c952c15
